version: '3.9'
services:
  postgres-db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=reservas_avaliacoes_api
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend-reservas_avaliacoes_api:lastest
    container_name: api-reservas_avaliacoes
    ports:
      - "8080:8080"
    environment:
      - RDS_HOSTNAME=postgres-db
      - RDS_PORT=5432
      - RDS_USERNAME=postgres
      - RDS_PASSWORD=admin
      - PROFILE=prod
    expose:
      - 8080
    volumes:
      - ./target:/app
    depends_on:
      - postgres-db
volumes:
  db_data: