apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: reservasavaliacoes-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reservasavaliacoes
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 90