apiVersion: v1
kind: Service
metadata:
  name: reservasavaliacoes-service
spec:
  type: NodePort
  selector:
    app: tech-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000