CREATE TABLE IF NOT EXISTS clientes (
    idcliente SERIAL NOT NULL PRIMARY KEY,
    nome CHARACTER(100) NOT NULL,
    email CHARACTER(100) NOT NULL,
    logradouro CHARACTER(200) NOT NULL,
    bairro CHARACTER(100) NOT NULL,
    cep CHARACTER(9) NOT NULL,
    complemento CHARACTER(100),
    numero CHARACTER(20) NOT NULL,
    uf CHARACTER(2) NOT NULL,
    cidade CHARACTER(100) NOT NULL,
    telefone CHARACTER(50) NOT NULL);
