app:
  name: reservas_avalicaoes_api
  replicaCount: 3
  image:
    repository: wolwer/reservas_avalicaoes_api
    tag: v3.0
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 8080
    targetPort: 8080
    nodePort: 30000
  database:
    url: jdbc:postgresql://postgres:5432/reservas_avaliacoes_api
    username:
      secretKeyRef:
        name: my-secret
        key: DATA_USERNAME
    password:
      secretKeyRef:
        name: my-secret
        key: DATA_PASSWORD
  springProfilesActive: prod

postgres:
  name: postgres
  replicaCount: 1
  image:
    repository: postgres
    tag: latest
  env:
    user:
      secretKeyRef:
        name: my-secret
        key: DATA_USERNAME
    password:
      secretKeyRef:
        name: my-secret
        key: DATA_PASSWORD
    db:
      configMapKeyRef:
        name: my-configmap
        key: DATA_DATABASE
  service:
    port: 5432
  pvc:
    name: postgres-pvc